services:
  backend:
    build: ./smart-dashboard-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./smart-dashboard-backend:/app
      - /app/node_modules

  frontend:
    build: ./smart-dashboard-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/usr/share/nginx/html
